### ISSUE TITLE
cannot import TUpleNode from autograd.container_types

### ISSUE THREAD

**Issue by aubreychen9012** [mattjj/svae#11]
I was trying to import svae.svae and got the error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "svae/svae.py", line 5, in <module>
    from util import split_into_batches, get_num_datapoints
  File "svae/util.py", line 12, in <module>
    from autograd.container_types import TupleNode, ListNode
ImportError: cannot import name TupleNode

and checked autograd.container_types, this TupleNode is not available there, or did I miss something? Thanks for any help.

**Comment by mattjj** [comment]
I think this is probably related to the fact that this code requires an old version of autograd (see [the readme](https://github.com/mattjj/svae/blob/master/README.md)). 

By the way, I'm working on a newer version of this code (which will also fix some headaches and bugs in this version), but I'm not sure when I'll be able to open-source it. Maybe in the next month or two!

**Comment by anthonygualandri** [comment]
Hi Matt, just checking to see if the newer version referred to above is still in the works and how far you are from completing it if it is. Thanks!
